// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe6ce-tt7NZDmxYaoDZu16iwUAb15X9X8',
    appId: '1:353302887560:web:b5f836059509a33450733d',
    messagingSenderId: '353302887560',
    projectId: 'ram-literature-v2',
    authDomain: 'ram-literature-v2.firebaseapp.com',
    storageBucket: 'ram-literature-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGJ6UQJsXuuil87kOUTzQBgjVAN0n79Fw',
    appId: '1:353302887560:android:f5a89502dafb419050733d',
    messagingSenderId: '353302887560',
    projectId: 'ram-literature-v2',
    storageBucket: 'ram-literature-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHoa_dWskkVeFEiQQbhwYY0UdA6Lz45Z0',
    appId: '1:353302887560:ios:b6fd631b286f7c8a50733d',
    messagingSenderId: '353302887560',
    projectId: 'ram-literature-v2',
    storageBucket: 'ram-literature-v2.firebasestorage.app',
    iosBundleId: 'com.literature.literature',
  );
}
